# Generated by Django 4.2.7 on 2024-05-05 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_total_hours_worked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='current_work_location',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='total_hours_worked',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='work_start_time',
        ),
    ]
