# Generated by Django 4.2.7 on 2024-04-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20240324_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Ten adres email jest już używany. Proszę użyć innego adresu.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
