# Generated by Django 4.2.7 on 2024-05-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email address is already in use. Please use a different address.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
