# Generated by Django 4.2.7 on 2024-06-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Email is already in use. Use a different one'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
