# Generated by Django 3.2.20 on 2024-04-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksession', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
