# Generated by Django 3.2.20 on 2024-04-07 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksession', '0004_delete_liveworksession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksession',
            name='total_time',
        ),
    ]
