# Generated by Django 4.2.7 on 2024-04-11 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('worksession', '0005_remove_worksession_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksession',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
