# Generated by Django 4.2.7 on 2024-05-19 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_personnummer'),
        ('workplace', '0002_alter_workplace_postal_code_and_more'),
        ('worksession', '0008_alter_worksession_end_time_alter_worksession_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksession',
            name='end_time',
            field=models.DateTimeField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='User profile'),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='workplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workplace.workplace', verbose_name='Workplace'),
        ),
    ]
