# Generated by Django 4.2.7 on 2024-05-19 07:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='postal_code',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message="Post code must be in the format 'XXX XX'.", regex='^\\d{3}\\s\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='street_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='The street number must be a number.', regex='^\\d+$')]),
        ),
    ]
