# Generated by Django 3.2.20 on 2024-03-23 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='street',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Nazwa ulicy nie moze zawierac liczby.', regex='^[A-Za-z\\s]+$')]),
        ),
    ]
