# Generated by Django 4.2.7 on 2024-04-11 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_user'),
        ('livesession', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livesession',
            name='user',
        ),
        migrations.AddField(
            model_name='livesession',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Profil'),
        ),
    ]
