# Generated by Django 4.2.7 on 2024-04-11 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workplace', '0001_initial'),
        ('livesession', '0002_remove_livesession_user_livesession_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Profil użytkownika'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='workplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workplace.workplace', verbose_name='Miejsce pracy'),
        ),
    ]
