# Generated by Django 4.2.7 on 2024-05-19 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_personnummer'),
        ('workplace', '0002_alter_workplace_postal_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livesession', '0003_livesession_user_alter_livesession_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livesession',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='User profile'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='workplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workplace.workplace', verbose_name='Workplace'),
        ),
    ]
